name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  RUBYOPTS: "--disable-did-you-mean"
  JAVA_OPTS: "-Djava.security.egd=file:/dev/urandom"

jobs:
  rspec:
    name: Ruby ${{ matrix.ruby }} Specs
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.0", "3.1", "3.2", "3.3", "3.4", "jruby"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake

  rubocop:
    name: RuboCop Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
          bundler-cache: true

      - name: Run RuboCop
        run: bundle exec rubocop --format github
