name: Test

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby_version:
          - 2.5
          - 2.6
          - 2.7
          - jruby-9.2.12.0

    name: Ruby ${{ matrix.ruby_version }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true

      - name: RSpec
        run: bundle exec rake
